---
title: "qRT-PCR ISG Expression in IFN Treated IFNAR1 or IFNLR1 KO Cells"
subtitle: 'Thesis_Code_2: Figures 9'
output: 
  html_document:
    keep_md: true
---

```{r,warning=FALSE,message=FALSE}

library(tidyverse)
library(plyr)
library(gridExtra) #for the grid.arrange
library(grid) #for the title in grid.arrange
library(data.table)
#library(ComplexHeatmap)
library(circlize)
```

```{r}
tccr = read.csv2("042519.csv", header = TRUE,stringsAsFactors = FALSE, sep=",", dec=".")
#remove the first column
m=colnames(tccr)[1] 
tccr[,m] <-NULL
# Converts all values between 0 and 1 to 1. Preserves NA values.
# lapply applies the provided function on each of the columns
tccr[,4:14] <- lapply(tccr[,4:14], function(aCol) {
  # sapply takes each value of a column and applies the function which does the correction.
  sapply(aCol, function(x) {
    if (x > 1 || is.na(x)) x else 1
  })
})
#Transform all variables into log
tccr[,4:14] <- log10(tccr[,4:14])
#Add an ID to know which row to remove when removing outliers
tccr$ID = seq(1,dim(tccr)[1],by=1)
tccr
```


```{r}
# This function takes the dataframe for a measure (3 values) and a variable(for instance M) and:
# Identifies among the 3 measures one outlier.
# The criterium for classifying a measure as an outlier is making a candidate list:the maximum and minimum.
# for those two candidates values, to recalculate the standard deviation without that candidate
# If the sd suffers a greater decrease in a factor, that is, if original sd / new sd > factor
# Then the point is classified as an outlier and it will be treated afterwards (outside the function, replacing it with NA)
outlierPoint <- function(x,variable){

# factor is the sensibility for classifying outliers.
# in the data available, the results are the following:
# out of 396 measures of 3 values (with no log10 transformation):
# with factor =5, 119 outliers were found, that is 119/396 = 30%
# with factor =10, 69 outliers were found, that is 69/396 = 17%
# with factor =50, 19 outliers were found, that is 19/396 = 5%
# with factor =100, 12 outliers were found,  that is 12/396 = 3%
# with factor =150, 9 outliers were found, that is 9/396 = 2%
  
# ADJUST HERE THE FACTOR:
factor=5

debug<-F
#f<-by(tccr[,4],tccr[,1:3],outlierPoint)


(mini<-min(x[,variable]))
(maxi<-max(x[,variable]))
  
if(debug) message("original mean = ",mean(x[,variable]))
if(debug) message("original sd = ",sd(x[,variable]))

originalsd<-sd(x[,variable])

(maxi_i <-which(x[,variable]==maxi))
(mini_i <-which(x[,variable]==mini))
(below_maxi_i<-which(x[,variable]<maxi))
(above_mini_i<-which(x[,variable]>mini))
  
if(debug) message("index of max = ",maxi_i)
if(debug) message("index of min = ",mini_i)

(removed_max <- x[-maxi_i,])
(removed_min <- x[-mini_i,])

(new_reduced_mean <- mean(removed_max[,variable]))
(new_increased_mean <- mean(removed_min[,variable]))


if(debug) message("mini=",mini, "increased mean=",new_increased_mean)
if(debug) message("maxi=",maxi, "reduced mean=",new_reduced_mean)
min_sd<- sd(removed_min[,variable])
if(debug) message("sd increased mean:",sd(removed_min[,variable])," -:",originalsd/min_sd)
max_sd<-sd(removed_max[,variable])
if(debug) message("sd reduced mean:",sd(removed_max[,variable])," -:",originalsd/max_sd)   
if(is.na(min_sd)){return(-1)}
if(is.na(max_sd)){return(-1)}


#Do we have an decrease of sd by a factor, (which is good)? then the point is an outlier
if(originalsd/min_sd >factor){
  return(x[mini_i,]$ID)
  
}
#Do we have an decrease of sd by a factor, (which is good)? then the point is an outlier
if(originalsd/max_sd >factor){
  return(x[maxi_i,]$ID)
  
}
return(-1)

}

#t <- tccr[tccr$Treatment=='IFNB+/IAV+' & tccr$Cell.Type=='IFNAR1-/-' & tccr$Timepoint==24,]
#outlierPoint(t,'M')

```

```{r}
treat <- unique(tccr$Treatment)
cell <- unique(tccr$Cell.Type)
time <- unique(tccr$Timepoint)
(rows <- colnames(tccr)[4:14])
total=0
#not able to apply by method with the function outlierPoint, therefore slow brute force with for....
message("The following are the outliers detected (variable -> row number)")
for(a in rows){
  for(i in treat){
    for(j in cell){
      for(k in time){
        #message(a," - ",i," - ",j," - ", k)
        t <- tccr[tccr$Treatment==i & tccr$Cell.Type==j & tccr$Timepoint==k,]
        res<-outlierPoint(t,a)
        if(res>-1){ 
          total=total+1
          #An outlier was found, remove it.
          tccr[res,a]=NA
          message(a," -> ",res)
        }
      }
    }
  }
}
total
```

```{r}
tccr
#saveRDS(tccr, "tccR_removed_outliers.rds")
```




```{r,warning=FALSE,message=FALSE}
#+++++++++++++++++++++++++
# Function to calculate the mean and the standard deviation and also (mean +sd and  
# mean-sd) for each group
#+++++++++++++++++++++++++
# data : a data frame
# varname : the name of a column containing the variable
  #to be summariezed
# groupnames : vector of column names to be used as
  # grouping variables

#sem = sd/sqrt(n)
#cimin = mean - 2*sem
#cimax = mean + 2*sem


data_summary <- function(data, varname, groupnames){
  
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      max = mean(x[[col]], na.rm=TRUE)+sd(x[[col]], na.rm=TRUE),
      min = mean(x[[col]], na.rm=TRUE)-sd(x[[col]], na.rm=TRUE),
      cimin = mean(x[[col]], na.rm=TRUE)-2*sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])),
      cimax = mean(x[[col]], na.rm=TRUE)+2*sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]]))
      )
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
 return(data_sum)
}
```

```{r}
create_df <- function(value){
  df_ <- data_summary(tccr, varname=value, groupnames=c("Cell.Type","Timepoint","Treatment"))
  df_[order(df_$Cell.Type,df_$Timepoint,df_$Treatment),]
  time <- c(seq(9,14,by=1),seq(21,26,by=1))
  df_$Timepoint2 = c(time,time,time)
  #reorder factors please to adquate to the plot requirements
  df_$Cell.Type=factor(df_$Cell.Type, levels=c("Wildtype", "IFNAR1-/-", "IFNLR1-/-"))
  return(df_)
}

dfM<-create_df('M')
dfIFNA<-create_df('IFNA')
dfIFNb<-create_df('IFNb')
dfIL29<-create_df('IL29')
dfIl28a<-create_df('Il28a')
dfMXA<-create_df('MXA')
dfRIGI<-create_df('RIGI')
dfISG15 <- create_df('ISG15')
dfIFIT2 <- create_df('IFIT2')
dfIFITM1 <- create_df('IFITM1')
dfRantes <- create_df('Rantes')
dfM
```

```{r}

tccr
dfM


#Analysis 3: Comparing WT, INFAR1-/-, INFLR1-/- for IAV- and IFN-, IFNB+, and INFL+

# list1 <- c('IFN-/IAV-','IFN-/IAV+')
# list2 <- c('IFNB+/IAV+','IFN-/IAV+','IFNL+/IAV+')

list3 <- c('IFN-/IAV-','IFNB+/IAV-','IFNL+/IAV-')

g_all2 <- function(type,l, setMaxMin=T){

esi = 0.8
tsi = 15
asi = 1.3
ewidth=.4
title_size=40
df<- get(paste("df",type,sep=""))
 treatment <- unique(df$Treatment)
  

q<-df[df$Treatment %in% l,]  %>%
  ggplot(aes_string(x="Cell.Type",y=type,ymin="cimin", ymax="cimax",fill = "Treatment")) +
  geom_bar(stat='identity', position = "dodge") +
  geom_errorbar(width=0.4,position=position_dodge(0.9), size=0.8)+
  scale_fill_manual(values=c("IFN-/IAV-"="black", "IFN-/IAV+"="gray","IFNB+/IAV-"="red","IFNB+/IAV+"="Orange", "IFNL+/IAV-"="Blue", "IFNL+/IAV+"="Purple"), breaks=treatment)+
   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
       text = element_text(size=tsi),
         axis.ticks = element_line(colour = "black", size = asi),
       axis.line = element_line(colour = 'black', size = asi),
panel.background = element_blank())+
  theme(plot.title = element_text(hjust = 0.5,size=title_size))+
  labs(y=paste('Log10 Relative Expression'), x = type)+
  facet_grid(~Timepoint, space="free", scales="free") 



if(setMaxMin){
  q <- q+ ylim(min(-0.5),max(3))
}

return(q)


  
}




```

```{r}
 #  1. M  
 #  2. IFNA  
 #  3. IFNb 
 #  4. IL29  
 #  5. Il28a 
 #  6. MXA   
 #  7. RIGI 
 #  8. ISG15
 #  9. IFIT2  
 # 10. IFITM1
 # 11. Rantes

p1<-g_all2('M',list3)
p2<-g_all2('IFNA',list3)
p3<-g_all2('IFNb',list3)
p4<-g_all2('IL29',list3)
p5<-g_all2('Il28a',list3)
p6<-g_all2('MXA',list3)
p7<-g_all2('RIGI',list3)
p8<-g_all2('ISG15',list3)
p9<-g_all2('IFIT2',list3)
p10<-g_all2('IFITM1',list3)
p11<-g_all2('Rantes',list3)


p1
p2
p3
p4
p5
p6
p7
p8
p9
p10
p11



p6
p8




# grid.arrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11, ncol = 4)



```
